project:
  type: book

bibliography: references.bib

book:
  title: "Driftsäkerhet"
  chapters:
    - index.qmd
    - rams.qmd
    - tillganglighet.qmd
    - tillforlitlighet.qmd
  appendices:
    - formelsamling.qmd

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrreprt
